spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    format_sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
